# Generated by Django 5.0.6 on 2024-09-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('material_type', models.CharField(choices=[('PDF', 'PDF'), ('Video', 'Video'), ('Text', 'Text')], max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
