# Generated by Django 5.1.1 on 2024-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling', '0003_alter_counselingmaterial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingmaterial',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
